nix/bootstrap.sh
nix/shell.sh
package.yaml
src/LndClient/Data/Invoice.hs
src/LndClient/RPC.hs
test/LndClient/RPCSpec.hs

Add fields to invoice model and update tests:
```
memo :: Maybe Text,
paymentRequest :: Maybe Text,
fallbackAddr :: Maybe Text,
cltvExpiry :: Text,
private :: Maybe Bool,
addIndex :: Maybe Text,
state :: Maybe Text
```

Update fields and tests

---

src/LndClient/Data/Newtypes.hs

Int -> Word64 for unsigned values

---

src/LndClient/Data/Invoice.hs
src/LndClient/Data/LndEnv.hs
src/LndClient/Data/Newtypes.hs
src/LndClient/RPC.hs
test/LndClient/RPCSpec.hs

- use gRPC for subscribeInvoices
- local tests are green (if open fresh nix shell and run `stack test`)
- a lot of TODOs and places to improve

subscribeInvoices gRPC

---

src/LndClient/Class.hs
src/LndClient/Data/AddInvoice.hs
src/LndClient/Data/Newtypes.hs
src/LndClient/Data/Types.hs
src/LndClient/RPC.hs
src/LndClient/Utils.hs

with couple of examples (for `addInvoice` RPC)

FromGrpc and ToGrpc multi-parameter type classes 

---

nix/pkg.nix
src/LndClient/Data/LndEnv.hs
src/LndClient/RPC.hs
test/LndClient/RPCSpec.hs

`LazyInitWallet` and `LazyUnlockWallet` composite RPC helpers. Will be super useful on applications, to call on startup. Will be useful for tests as well.

LazyInitWallet and LazyUnlockWallet composite RPC helpers

---

src/LndClient/Data/Invoice.hs

Getting invoice state in InvoiceSubscription

Invoice state

---

package.yaml
src/LndClient/Data/LndEnv.hs
src/LndClient/Data/Type.hs

Smart constructor for LndEnv initialization

---

.circleci/config.yml
src/LndClient/Data/LndEnv.hs
src/LndClient/RPC.hs

- katipAddLndContext util
- show LndHost and LndPort on RPC
- add CI nix cache

2020 06 08

---

src/LndClient/Data/Type.hs
src/LndClient/RPC.hs

- introduce *genStreamHandler*
- remove *fail* from subscription handlers
- throw and catch exceptions from subscription handlers

2020 06 10

---

nix/export-test-envs.sh
src/LndClient/Data/LndEnv.hs
src/LndClient/Data/Newtype.hs
src/LndClient/RPC/Generic.hs
test/LndClient/RPCSpec.hs

- Aeson parser for LndEnv + simple test
- Configurable optional gRPC timeouts
- removed redundant RawConfig sources

2020 10 07 it 0

---

lnd-client.cabal
nix/shell.nix
src/LndClient/Data/Newtype.hs
src/LndClient/Data/Payment.hs
src/LndClient/Data/TrackPayment.hs
src/LndClient/RPC/Generic.hs
src/LndClient/RPC/Katip.hs
src/LndClient/RPC/Silent.hs
src/LndClient/RPC/TH.hs
src/LndClient/Watcher.hs
test/LndClient/RPCSpec.hs
test/LndClient/TestApp.hs
test/LndClient/TestOrphan.hs

- new RPC `trackPaymentV2` 
- pretty public opaque `Watcher` newtype

2020 11 02 it 0

---

nix/shell.nix
nix/shell.sh
nix/spawn-test-deps.sh
stack.yaml

fix nix shell

---

lnd-client.cabal
src/LndClient/Data/InitWallet.hs
src/LndClient/Data/LndEnv.hs
src/LndClient/Data/OpenChannel.hs
src/LndClient/Data/PayReq.hs
src/LndClient/Data/Peer.hs
src/LndClient/Data/SendPayment.hs
src/LndClient/Data/SubscribeInvoices.hs
src/LndClient/Data/TrackPayment.hs
src/LndClient/Data/UnlockWallet.hs
src/LndClient/LndTest.hs
src/LndClient/RPC/Generic.hs
src/LndClient/Watcher.hs
stack.yaml
test/LndClient/RPCSpec.hs
test/LndClient/TestApp.hs

- a lot of additional RPC logging
- `LndClient.LndTest` test suite with `LndTest` class and utils
- `trackPaymentV2` method is not really working (previous test was wrong), but we are not using this method atm

2021 02 01 it 0

---

src/LndClient/LndTest.hs
test/LndClient/RPCSpec.hs

- Opening test channel improvements
- New `syncPendingChannels` test utility

2021 02 05 it 0

---

lnd-client.cabal
src/LndClient/Class.hs
src/LndClient/Data/ChannelPoint.hs
src/LndClient/Data/CloseChannel.hs
src/LndClient/Data/ClosedChannel.hs
src/LndClient/Data/ForceClosedChannel.hs
src/LndClient/Data/Newtype.hs
src/LndClient/Import.hs
src/LndClient/Util.hs
src/LndGrpc/Orphan.hs

- newtypes `ChannelFundingTxId` `ChannelFundingOutputIndex` `ChannelClosingTxId`
- `txIdParser` uility to parse LND text representation of bitcoin transaction ids

2021 02 18 it 0

---

lnd-client.cabal
package.yaml
src/LndClient.hs
src/LndClient/Data/Channel.hs
src/LndClient/Data/ChannelPoint.hs
src/LndClient/Data/CloseChannel.hs
src/LndClient/Data/ClosedChannel.hs
src/LndClient/Data/ForceClosedChannel.hs
src/LndClient/Data/Kind.hs
src/LndClient/Data/Newtype.hs
src/LndClient/Data/SubscribeChannelEvents.hs
src/LndClient/Import.hs

- Newtypes for TxId and Vout
- Generic PendingUpdate

2020 02 18 it 1

---

src/LndClient/Data/LndEnv.hs
src/LndClient/Data/Type.hs
src/LndClient/LndTest.hs
src/LndClient/RPC/Generic.hs
src/LndClient/RPC/Katip.hs
src/LndClient/RPC/Silent.hs
src/LndClient/Watcher.hs

Use LoggingStrategy from LndEnv to make logging more configurable just in place, will be useful to avoid spam from watchers.

B1 m2 2241

---

nix/overlay/lnd.nix
src/LndClient/Data/Newtype.hs
src/LndClient/LndTest.hs
src/LndClient/RPC/Generic.hs
src/LndClient/RPC/Katip.hs
src/LndClient/RPC/Silent.hs
src/LndClient/RPC/TH.hs
src/LndClient/Watcher.hs
test/LndClient/RPCSpec.hs

- Upgrade Lnd 0.13.0
- SubscribeSingleInvoice RPC
- Added some TODOs

2021 06 16 it 0

---

nix/overlay/lnd.nix
src/LndClient/LndTest.hs
src/LndClient/Watcher.hs

- using lightninglabs lnd 0.13
- `setupZeroChannels` improvements

B1 m2 2304

---

lnd-client.cabal
package.yaml
src/LndClient/Class.hs
src/LndClient/Data/Channel.hs
src/LndClient/Data/PendingChannel.hs
src/LndClient/Data/Type.hs
src/LndClient/Import/External.hs

Added `LnInitiator` type, decode it from LnGrpc active and pending channels.

2021 09 08 it 0

---

.gitignore
cabal.project
default.nix
lnd-client.cabal
nix/shell.sh
nix/sources.json
package.yaml
prof/LndClient/Main.hs
script/profile.sh
shell.nix
src/LndClient/Data/LndEnv.hs
src/LndClient/Data/Type.hs
src/LndClient/Log.hs
src/LndClient/Orphan.hs
src/LndGrpc/Client.hs
tkit/LndClient/TestApp.hs

- Upgrade http2 and grpc libs, nixpkgs and haskellNix.
- Grpc client memory leak fixed with package upgrades.
- Add --profile option for nix shell.

B1 m2 5509

---

lnd-client.cabal
package.yaml
src/LndClient/Data/ChannelBackup.hs
src/LndClient/Data/ChannelPoint.hs
src/LndClient/Log.hs
src/LndClient/RPC/Katip.hs
src/LndClient/RPC/Silent.hs
src/LndClient/RPC/TH.hs
test/LndClient/ChanBakSpec.hs
test/LndClient/RPCSpec.hs

Some methods related to static channels backups with tests:
- exportChannelBackup
- exportAllChannelBackups
- restoreChannelBackups

B1 m2 5838

---

LICENSE
lnd-client.cabal
package.yaml

https://hackage.haskell.org/package/lnd-client-0.1.0.1

new release

---

src/LndClient/Data/LndEnv.hs
src/LndClient/Data/Newtype.hs
src/LndClient/Data/PayReq.hs
src/LndClient/Import/External.hs
src/LndClient/LndTest.hs
src/LndClient/RPC/TH.hs
src/LndClient/Util.hs
test/LndClient/RPCSpec.hs

* Refactor rest of newtypes to use Natural type if applicable
* Remove fromIntegral and safeFromIntegral funcs

Replace fromIntegral and safeFromIntegral with from and tryFrom

---

cabal.project
lnd-client.cabal
package.yaml

B1 m2 6004
